// Code generated by "stringer -type=errSkimPipeCode -output=errors_skim_pipe.gen.go"; DO NOT EDIT.

package cmd

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[errSkimPipeToNullC-0]
	_ = x[errSkimPipeSkStdinPipeC-1]
	_ = x[errSkimPipeSkStartC-2]
	_ = x[errSkimPipeFromRunC-3]
	_ = x[errSkimPipeCloseInpC-4]
	_ = x[errSkimPipeFromWaitC-5]
}

const _errSkimPipeCode_name = "errSkimPipeToNullCerrSkimPipeSkStdinPipeCerrSkimPipeSkStartCerrSkimPipeFromRunCerrSkimPipeCloseInpCerrSkimPipeFromWaitC"

var _errSkimPipeCode_index = [...]uint8{0, 18, 41, 60, 79, 99, 119}

func (i errSkimPipeCode) String() string {
	if i < 0 || i >= errSkimPipeCode(len(_errSkimPipeCode_index)-1) {
		return "errSkimPipeCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _errSkimPipeCode_name[_errSkimPipeCode_index[i]:_errSkimPipeCode_index[i+1]]
}
